const STYLE_ID = 'dsh-mission-control-styles'

const CSS = `
.mc-action{align-items:center;background:transparent;border:1px solid color-mix(in srgb,currentColor 16%,transparent);border-radius:8px;color:inherit;cursor:pointer;display:inline-flex;font:inherit;gap:7px;min-height:30px;padding:5px 10px}.mc-action:hover{background:color-mix(in srgb,currentColor 7%,transparent)}.mc-action--rail{border:0;height:34px;justify-content:center;padding:5px;width:34px}.mc-action__mark{font-size:14px;line-height:1}
.mc-panel{background:var(--dsh-surface,Canvas);border-block:1px solid color-mix(in srgb,currentColor 14%,transparent);color:inherit;display:grid;grid-template-rows:38px minmax(0,1fr);height:100%;min-height:0;overflow:hidden}.mc-panel__header{align-items:center;border-bottom:1px solid color-mix(in srgb,currentColor 10%,transparent);display:flex;justify-content:space-between;padding:0 9px}.mc-panel__brand{align-items:center;display:flex;font-size:12px;gap:6px;min-width:0}.mc-panel__live{background:color-mix(in srgb,#24a36a 18%,transparent);border-radius:999px;color:#178653;font-size:9px;padding:2px 5px}.mc-panel__close{background:transparent;border:0;border-radius:6px;color:inherit;cursor:pointer;font-size:17px;height:28px;width:28px}.mc-panel__close:hover{background:color-mix(in srgb,currentColor 7%,transparent)}.mc-panel__idle{align-self:center;color:color-mix(in srgb,currentColor 60%,transparent);font-size:12px;padding:16px;text-align:center}
.mc-dashboard{display:grid;grid-template-rows:auto 34px minmax(0,1fr);height:100%;min-height:0;outline:none}.mc-dashboard__content{display:block;min-height:0;overflow:hidden}.mc-dashboard__empty{color:color-mix(in srgb,currentColor 58%,transparent);font-size:11px;padding:20px;text-align:center}.mc-tabs{border-bottom:1px solid color-mix(in srgb,currentColor 10%,transparent);display:flex;padding:0 8px}.mc-tabs button{background:transparent;border:0;border-bottom:2px solid transparent;color:inherit;cursor:pointer;font:inherit;font-size:11px;padding:7px 9px 6px}.mc-tabs button[aria-selected=true]{border-bottom-color:#3b82f6;color:#2563eb}.mc-tabs span{background:color-mix(in srgb,currentColor 8%,transparent);border-radius:999px;font-size:9px;margin-left:3px;padding:1px 4px}
.mc-hud{align-items:center;border-bottom:1px solid color-mix(in srgb,currentColor 10%,transparent);display:grid;gap:5px;grid-template-columns:minmax(0,1fr) auto;padding:7px 9px}.mc-hud__identity{align-items:center;display:flex;gap:7px;grid-column:1/-1;min-width:0}.mc-hud__identity div{display:flex;flex-direction:column;min-width:0}.mc-hud__identity strong{font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mc-hud__identity span{color:color-mix(in srgb,currentColor 58%,transparent);font-size:9px}.mc-connection{background:#94a3b8;border-radius:50%;flex:none;height:7px;width:7px}.mc-connection--live{background:#22c55e;box-shadow:0 0 6px #22c55e}.mc-connection--reconnecting,.mc-connection--connecting{background:#eab308}.mc-connection--unavailable{background:#ef4444}.mc-metric{display:flex;flex-direction:column}.mc-metric span,.mc-cost>span{color:color-mix(in srgb,currentColor 55%,transparent);font-size:8px;text-transform:uppercase}.mc-metric strong{font-size:16px;font-variant-numeric:tabular-nums}.mc-cost{align-items:flex-end;display:flex;flex-direction:column;position:relative}.mc-cost>strong{color:#15945c;font-size:14px;font-variant-numeric:tabular-nums}.mc-cost--partial>strong{color:#b7791f}.mc-cost--unavailable>strong{color:inherit}.mc-cost>small{display:none}.mc-cost details{font-size:9px}.mc-cost summary{color:#3b82f6;cursor:pointer}.mc-cost__details{background:var(--dsh-surface,Canvas);border:1px solid color-mix(in srgb,currentColor 18%,transparent);border-radius:8px;box-shadow:0 8px 24px #0003;display:flex;flex-direction:column;gap:4px;max-height:220px;overflow:auto;padding:8px;position:absolute;right:0;top:46px;width:250px;z-index:20}.mc-cost__model{background:color-mix(in srgb,currentColor 4%,transparent);border-radius:5px;display:flex;flex-direction:column;gap:2px;overflow-wrap:anywhere;padding:5px}.mc-hud__counts{color:color-mix(in srgb,currentColor 62%,transparent);display:flex;font-size:9px;gap:7px;grid-column:1/-1}.mc-hud__warning{background:#f59e0b16;border:1px solid #f59e0b55;border-radius:5px;color:#a16207;font-size:9px;grid-column:1/-1;padding:3px 5px}
.mc-agent-tree,.mc-tools{height:100%;min-height:0;overflow:auto}.mc-agent-tree__all{background:transparent;border:0;color:#3b82f6;cursor:pointer;font-size:10px;padding:8px 10px;text-align:left;width:100%}.mc-agent-tree__rows{padding:0 6px 8px}.mc-agent-row{align-items:center;background:transparent;border:0;border-radius:6px;color:inherit;cursor:pointer;display:flex;gap:7px;min-height:38px;padding-block:5px;padding-inline-end:7px;text-align:left;width:100%}.mc-agent-row:hover{background:color-mix(in srgb,currentColor 6%,transparent)}.mc-agent-row--selected{background:color-mix(in srgb,#3b82f6 12%,transparent)}.mc-agent-row__status{background:#94a3b8;border-radius:50%;flex:none;height:7px;width:7px}.mc-agent-row--responding .mc-agent-row__status,.mc-agent-row--tool .mc-agent-row__status{background:#22c55e;box-shadow:0 0 5px #22c55e}.mc-agent-row--error .mc-agent-row__status{background:#ef4444}.mc-agent-row__copy{display:flex;flex-direction:column;min-width:0}.mc-agent-row__copy strong{font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mc-agent-row__copy span{color:color-mix(in srgb,currentColor 56%,transparent);font-size:9px}
.mc-tools{display:grid;grid-template-rows:32px minmax(0,1fr);position:relative}.mc-tools>header{align-items:center;border-bottom:1px solid color-mix(in srgb,currentColor 8%,transparent);display:flex;font-size:10px;justify-content:space-between;padding:0 9px}.mc-tools__log{min-height:0;overflow:auto;padding:7px}.mc-tools__empty{color:color-mix(in srgb,currentColor 55%,transparent);font-size:10px;text-align:center}.mc-tool{background:color-mix(in srgb,currentColor 3%,transparent);border:1px solid color-mix(in srgb,currentColor 11%,transparent);border-left:3px solid #94a3b8;border-radius:6px;margin-bottom:6px;padding:7px}.mc-tool--running{border-left-color:#22c55e}.mc-tool--error{border-left-color:#ef4444}.mc-tool__head,.mc-tool__meta{display:flex;gap:6px;justify-content:space-between}.mc-tool__head{font-size:10px}.mc-tool__head span,.mc-tool__meta{color:color-mix(in srgb,currentColor 56%,transparent);font-size:8px}.mc-tool__meta{margin-top:4px}.mc-tool__preview{background:color-mix(in srgb,currentColor 5%,transparent);border-radius:4px;margin-top:5px;overflow:auto;padding:5px}.mc-tool__preview small{color:#b7791f}.mc-tool__preview pre{font:9px/1.4 ui-monospace,SFMono-Regular,monospace;margin:3px 0;white-space:pre-wrap}.mc-tools__return{background:#168653;border:0;border-radius:999px;bottom:8px;color:white;cursor:pointer;justify-self:center;padding:5px 9px;position:absolute}
`

/** Install the browser stylesheet once per plugin fiber. */
export function installStyles(): () => void {
  const existing = document.getElementById(STYLE_ID)
  if (existing !== null) return () => {}
  const style = document.createElement('style')
  style.id = STYLE_ID
  style.textContent = CSS
  document.head.append(style)
  return () => { style.remove() }
}
