const STYLE_ID = 'dsh-mission-control-styles'

const CSS = `
.mc-action{align-items:center;background:transparent;border:1px solid color-mix(in srgb,currentColor 16%,transparent);border-radius:8px;color:inherit;cursor:pointer;display:inline-flex;font:inherit;gap:7px;min-height:30px;padding:5px 10px}.mc-action:hover{background:color-mix(in srgb,currentColor 7%,transparent)}.mc-action:disabled{cursor:not-allowed;opacity:.4}.mc-action--rail{border:0;height:34px;justify-content:center;padding:5px;width:34px}.mc-action__mark{font-size:14px;line-height:1}
[data-mission-control-panel-host]{box-sizing:border-box;flex:0 1 42%;max-height:55%;min-height:220px;overflow:hidden;width:100%}[data-mission-control-panel-host]:empty{display:none}.mc-panel{background:#0b1721;border-block:1px solid #20303d;color:#eaf2f8;display:grid;grid-template-rows:38px minmax(0,1fr);height:100%;min-height:0;overflow:hidden}.mc-panel__topbar{align-items:center;border-bottom:1px solid #20303d;display:flex;justify-content:space-between;padding:0 9px}.mc-panel__brand{align-items:center;display:flex;font-size:11px;font-weight:700;gap:6px;min-width:0}.mc-panel__brand>span:nth-child(2){overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mc-panel__live{background:#173c31;border-radius:999px;color:#75e6ac;font-size:8px;padding:2px 5px}.mc-panel__close{background:transparent;border:0;border-radius:6px;color:#9db0bb;cursor:pointer;font-size:16px;height:27px;width:27px}.mc-panel__close:hover{background:#172a36;color:#fff}.mc-panel__body{min-height:0;overflow:hidden}
.mc-dashboard{display:grid;grid-template-rows:auto 34px minmax(0,1fr);height:100%;min-height:0;outline:none}.mc-dashboard__content{min-height:0;overflow:hidden}.mc-dashboard__empty{color:#9bb0be;font-size:11px;padding:16px;text-align:center}.mc-tabs{align-items:end;border-bottom:1px solid #20303d;display:flex;padding:0 8px}.mc-tabs button{background:transparent;border:0;border-bottom:2px solid transparent;color:#8196a3;cursor:pointer;font-size:10px;height:34px;padding:0 10px}.mc-tabs button[aria-selected=true]{border-bottom-color:#6ad8a2;color:#eaf2f8}
.mc-hud{align-items:center;background:#0b1721;display:grid;gap:5px;grid-template-columns:minmax(0,1fr) auto auto;padding:7px 9px}.mc-hud__identity{align-items:center;display:flex;gap:6px;min-width:0}.mc-hud__identity div{display:flex;flex-direction:column;min-width:0}.mc-hud__identity strong{font-size:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mc-hud__identity div span{color:#8299a8;font-size:8px}.mc-connection{background:#8ba0ac;border-radius:50%;flex:none;height:6px;width:6px}.mc-connection--live{background:#54d895;box-shadow:0 0 7px #54d895}.mc-connection--reconnecting{background:#f4bc5e}.mc-connection--unavailable{background:#ef6b6b}.mc-metric{display:none}.mc-metric--prominent{display:flex;flex-direction:column;min-width:50px}.mc-metric span,.mc-cost>span{color:#8299a8;font-size:7px;text-transform:uppercase}.mc-metric strong{color:#7be2b1;font-size:14px;font-variant-numeric:tabular-nums}.mc-cost{display:flex;flex-direction:column;min-width:62px;position:relative}.mc-cost>strong{color:#77ddad;font-size:11px;font-variant-numeric:tabular-nums}.mc-cost--partial>strong{color:#f1c576}.mc-cost--unavailable>strong{color:#9db0bb}.mc-cost>small{color:#8fa5b3;font-size:7px}.mc-cost details{font-size:8px}.mc-cost summary{color:#8fc8e5;cursor:pointer;max-width:72px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mc-cost__details{background:#10222e;border:1px solid #355164;border-radius:6px;display:flex;flex-direction:column;gap:4px;max-height:160px;overflow:auto;padding:7px;position:absolute;right:0;top:42px;width:240px;z-index:20}.mc-cost__details>strong{color:#ffd98a}.mc-cost__model{background:#091821;border-radius:5px;display:flex;flex-direction:column;gap:2px;overflow-wrap:anywhere;padding:5px}.mc-hud__counts{color:#9db0bb;display:flex;font-size:8px;gap:5px;grid-column:1/-1}.mc-hud__warning{background:#4b3615;border-radius:4px;color:#ffd98a;font-size:8px;grid-column:1/-1;padding:2px 4px}
.mc-agents{height:100%;min-height:0;overflow:auto}.mc-agents__all{background:transparent;border:0;border-bottom:1px solid #20303d;color:#9db0bb;cursor:pointer;font-size:9px;padding:7px 10px;text-align:left;width:100%}.mc-agents__list{padding:4px 0}.mc-agent-row{align-items:center;background:transparent;border:0;color:#eaf2f8;cursor:pointer;display:flex;gap:6px;min-height:36px;padding-block:4px;padding-inline-end:8px;text-align:left;width:100%}.mc-agent-row:hover{background:#10222e}.mc-agent-row--selected{background:#143126}.mc-agent-row--error .mc-agent-row__status{color:#ef6b6b}.mc-agent-row__branch{color:#557586;font-size:9px;width:10px}.mc-agent-row__copy{display:flex;flex:1;flex-direction:column;min-width:0}.mc-agent-row__copy strong{font-size:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mc-agent-row__copy small{color:#8196a3;font-size:8px}.mc-agent-row__status{color:#62d9a1;font-size:10px}
.mc-tools{background:#0b1721;display:grid;grid-template-rows:32px minmax(0,1fr);height:100%;min-height:0;position:relative}.mc-tools>header{align-items:center;border-bottom:1px solid #20303d;display:flex;font-size:9px;justify-content:space-between;padding:0 9px}.mc-tools>header span{background:#1c303d;border-radius:999px;color:#9eb3bf;font-size:8px;padding:1px 5px}.mc-tools__log{min-height:0;overflow:auto;padding:6px}.mc-tools__empty{color:#8196a3;font-size:9px;text-align:center}.mc-tool{background:#0f202b;border:1px solid #253945;border-left:2px solid #557586;border-radius:6px;margin-bottom:5px;padding:6px}.mc-tool--running{border-left-color:#62d9a1}.mc-tool--error{border-left-color:#ef6b6b}.mc-tool__head,.mc-tool__meta{display:flex;justify-content:space-between}.mc-tool__head{font-size:9px}.mc-tool__head span{color:#90a4af;font-size:8px}.mc-tool__meta{color:#8196a3;font-size:8px;margin-top:3px}.mc-tool__preview{background:#071219;border-radius:4px;margin-top:4px;overflow:auto;padding:4px}.mc-tool__preview small{color:#f1c576}.mc-tool__preview pre{font:8px/1.4 ui-monospace,SFMono-Regular,monospace;margin:2px 0;white-space:pre-wrap}.mc-tools__return{background:#267655;border:1px solid #59c994;border-radius:999px;bottom:8px;color:white;cursor:pointer;font-size:9px;justify-self:center;padding:4px 8px;position:absolute}
`

/** Install the browser stylesheet once per plugin fiber. */
export function installStyles(): () => void {
  const existing = document.getElementById(STYLE_ID)
  if (existing !== null) return () => {}
  const style = document.createElement('style')
  style.id = STYLE_ID
  style.textContent = CSS
  document.head.append(style)
  return () => { style.remove() }
}
